/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSubmitRouteImport } from './routes/_app.submit'
import { Route as AppSopsRouteImport } from './routes/_app.sops'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPlaybooksRouteImport } from './routes/_app.playbooks'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppCoachingRouteImport } from './routes/_app.coaching'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitRoute = AppSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppRoute,
} as any)
const AppSopsRoute = AppSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/coaching': typeof AppCoachingRoute
  '/insights': typeof AppInsightsRoute
  '/playbooks': typeof AppPlaybooksRoute
  '/settings': typeof AppSettingsRoute
  '/sops': typeof AppSopsRoute
  '/submit': typeof AppSubmitRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/coaching': typeof AppCoachingRoute
  '/insights': typeof AppInsightsRoute
  '/playbooks': typeof AppPlaybooksRoute
  '/settings': typeof AppSettingsRoute
  '/sops': typeof AppSopsRoute
  '/submit': typeof AppSubmitRoute
  '/team': typeof AppTeamRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/coaching': typeof AppCoachingRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/playbooks': typeof AppPlaybooksRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sops': typeof AppSopsRoute
  '/_app/submit': typeof AppSubmitRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coaching'
    | '/insights'
    | '/playbooks'
    | '/settings'
    | '/sops'
    | '/submit'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/coaching'
    | '/insights'
    | '/playbooks'
    | '/settings'
    | '/sops'
    | '/submit'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/coaching'
    | '/_app/insights'
    | '/_app/playbooks'
    | '/_app/settings'
    | '/_app/sops'
    | '/_app/submit'
    | '/_app/team'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submit': {
      id: '/_app/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AppSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sops': {
      id: '/_app/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AppSopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbooks': {
      id: '/_app/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coaching': {
      id: '/_app/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachingRoute: typeof AppCoachingRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSopsRoute: typeof AppSopsRoute
  AppSubmitRoute: typeof AppSubmitRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachingRoute: AppCoachingRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSopsRoute: AppSopsRoute,
  AppSubmitRoute: AppSubmitRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
